---
title: "ScHiCcompare Vignette"
author: "My Nguyen"
date: "2024-07-12"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette ScHiCcompare}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# ScHiCcompare

### Data format

```{r, message=FALSE, warning=FALSE, echo=FALSE}
source("/Users/mynguyen/Documents/GitHub/scHiCcompare/Example/Source_code/01_ScHicCompare_Functions.R")
source("/Users/mynguyen/Documents/GitHub/scHiCcompare/Example/Source_code/01_ScHicCompare_updatedFunctions.R")
source("/Users/mynguyen/Documents/GitHub/scHiCcompare/Example/Source_code/imputation_methods.R")
library(HiCcompare)
```

```{r}
sc_txt(file_path = "/Users/mynguyen/Documents/GitHub/scHiCcompare/Example/Data/ODC", cell = 'ODC', position_dataset = 1, type='txt')
head(ODC_1)
```

### Input hi-c data and generate schic table input for the method


```{r cars, message=FALSE, results='hide', echo=FALSE}
### Input single cell hi-c in sparse format (.txt) from a path
scHiC.table_ODC = scHiC_table(file.path = "/Users/mynguyen/Documents/GitHub/scHiCcompare/Example/Data/ODC", cell.type = 'ODC', position.dataset =  1:50, type='txt', select.chromosome = 'chr22')

scHiC.table_MG = scHiC_table(file.path = "/Users/mynguyen/Documents/GitHub/scHiCcompare/Example/Data/MG", cell.type = 'MG', position.dataset =  1:50, type='txt', select.chromosome = 'chr22')
```

```{r, echo=FALSE}
DT::datatable(scHiC.table_ODC, options = list(scrollX = TRUE))
```



### Impute data

```{r, message=FALSE, warning=FALSE, results='hide'}
############################  Imputation ############################ 
imp.cc.table.1 <- Pooling_RF_impute(scHiC.table = scHiC.table_ODC, n.imputation = 10, outlier.rm = TRUE, main.Distances = 1:10000000, pool.style = 'progressive')

imp.cc.table.2 <- Pooling_RF_impute(scHiC.table = scHiC.table_MG, n.imputation = 10, outlier.rm = TRUE, main.Distances = 1:10000000, pool.style = 'progressive')
```


### Normalized data

```{r, message=FALSE, warning=FALSE}
## Bulk matrix in sparse format
bulk.imp.sparse.1 = na.omit(pseudo_bulkHic(scHiC.table = imp.cc.table.1, 
                                                     out = 'sparse'))
bulk.imp.sparse.2 = na.omit(pseudo_bulkHic(scHiC.table = imp.cc.table.2,
                                                      out = 'sparse'))


## Jointly normalize data for a single chromosome by Loess HiCcompare
library(HiCcompare)
#create the `hic.table` object
bulk.hic.table <- create.hic.table(bulk.imp.sparse.1, bulk.imp.sparse.2, chr = 'chr22', scale = F)
#jointly normalize data for a single chromosome
hic.table_normalize <- hic_loess(bulk.hic.table, Plot = T, Plot.smooth = F)
```

### Differential detection

```{r, message=FALSE, warning=FALSE}

### Find differences
hic.table.result <- BulkHiC_compare(norm.hic.table = hic.table_normalize, D.interval = 'full',
                                    fprControl.logfc = 0.8, Plot = T)
```


